# Reference: https://github.com/cv516Buaa/tph-yolov5/blob/main/models/yolov5l-xs-tr-cbam-spp-bifpn.yaml

# Parameters
nc: 80  # number of classes
depth_multiple: 0.67  # model depth multiple
width_multiple: 1.00  # layer channel multiple

  

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P6/64
   [-1, 3, C3, [1024]],
   [-1, 1, CBAM, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 10
  ]

head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 14 (P4/16-medium)
   [-1, 1, CBAM, [512]],

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 19 (P3/8-small)
   [-1, 1, CBAM, [256]],

   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 2], 1, Concat, [1]],  # cat backbone P2
   [-1, 3, C3, [128, False]],  # 24 (P2/4-xsmall)
   [-1, 1, CBAM, [128]],

   [-1, 1, Conv, [128, 3, 2]],
   [[-1, 21], 1, Concat, [1]],  # cat head P3
   [-1, 3, C3, [256, False]],  # 28 (P3/8-small)
   [-1, 1, CBAM, [256]],

   [23, 2, C3STR, [128, False]],  # 30 (P2/4-xsmall)
   [30, 2, C3STR, [128, False]],  # 31 (P2/4-xsmall)
   [31, 2, C3STR, [128, False]],  # 32 (P2/4-xsmall)
   [[-1, 25], 1, Concat, [1]],  # cat head P3
   [-1, 1, NAM_Attention, [256]],

   [27, 2, C3STR, [256, False]],  # 35 (P3/8-small)
   [35, 2, C3STR, [256, False]],  # 36 (P3/8-small)
   [36, 2, C3STR, [256, False]],  # 37 (P3/8-small=
   [[-1, 29], 1, Concat, [1]],  # cat head P3
   [-1, 1, NAM_Attention, [512]],

   [[34,39], 1, Detect, [nc]],  # Detect(P2, P3, P4, P5)
  ]
 