# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
depth_multiple: 0.67  # model depth multiple
width_multiple: 1.00  # layer channel multiple

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, CBAM, [1024]] # 9
  - [-1, 1, SPPF, [1024, 5]]  # 10

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 13
  - [-1,1, CBAM, [512]] # 14

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 17 (P3/8-small)
  - [-1,1, CBAM, [256]] # 18

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]  # cat backbone P2
  - [-1, 3, C2f, [128]]  # 21 (P3/8-small)
  - [-1,1, CBAM, [128]] # 22
  # upsampling 
  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 18], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [256]]  # 25 (P4/16-medium)
  - [-1,1, CBAM, [256]] # 26
  # concatenating
  - [20, 2, C3STR, [128, False]]  # 27 (xsmall)
  - [27, 2, C3STR, [128, False]]  # 28 (xsmall)
  - [28, 2, C3STR, [128, False]]  # 29 (xsmall)
  - [[-1, 22], 1, Concat, [1]]  # cat head xsmall
  - [-1, 1, NAM_Attention, [256]] # 31

  - [24, 2, C3STR, [256, False]]  # 32 (small)
  - [31, 2, C3STR, [256, False]]  # 33 (small)
  - [32, 2, C3STR, [256, False]]  # 34 (small)
  - [[-1, 26], 1, Concat, [1]]  # cat head small
  - [-1, 1, NAM_Attention, [512]] # 36

  - [[31, 36], 1, Detect, [nc]]  # Detect(P3, P4, P5)